### ISSUE TITLE
npm start breaks on newest version of node

### ISSUE THREAD

**Issue by lberge17** [learn-co-curriculum/react-hooks-props-destructuring#5]
### Canvas Link

https://learning.flatironschool.com/courses/5263/assignments/219917?module_item_id=512727

### Concern

On the latest version of node that students are instructed to install (https://github.com/learn-co-curriculum/phase-0-macos-env-nodejs), the lab breaks when running npm start. Lab works on v16.17.0 and breaks for me on 17.9.1, 18.13.0, and 19.4.0. Error message from 19.4.0 provided in additional context.

### Additional Context

Starting the development server...

/Users/laura/Flatiron/labs/react-hooks-props-destructuring/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/Users/laura/Flatiron/labs/react-hooks-props-destructuring/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/laura/Flatiron/labs/react-hooks-props-destructuring/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/laura/Flatiron/labs/react-hooks-props-destructuring/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/laura/Flatiron/labs/react-hooks-props-destructuring/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/laura/Flatiron/labs/react-hooks-props-destructuring/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/laura/Flatiron/labs/react-hooks-props-destructuring/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/laura/Flatiron/labs/react-hooks-props-destructuring/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/laura/Flatiron/labs/react-hooks-props-destructuring/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v19.4.0

**Comment by lizbur10** [comment]
@lberge17 I've pushed up a change that I believe fixes this problem. It should now work for either Node 16 or Node 18. I'll leave this issue open until we get confirmation.
